# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20161111_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='like_photos',
        ),
    ]
