# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20161111_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoReply',
            new_name='PhotoComment',
        ),
    ]
