# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20161111_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='photo.PhotoTag'),
        ),
    ]
