# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20161111_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photo/origin_photo'),
        ),
    ]
